package com.luigimoro.spring.tutorial.dynamodb.dao.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "ProductInfo")
public class ProductInfo {
    private String id;
    private String msrp;
    private String cost;

    public ProductInfo(String cost, String msrp) {
        this.setCost(cost);
        this.setMsrp(msrp);
    }

    public ProductInfo() {}


    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "IndexName2")
    @DynamoDBAttribute
    public String getId() {
        return id;
    }

    @DynamoDBIndexRangeKey(globalSecondaryIndexNames = {"IndexName", "IndexName2"})
    @DynamoDBAttribute
    public String getMsrp() {
        return msrp;
    }
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "IndexName")
    @DynamoDBAttribute
    public String getCost() {
        return cost;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setMsrp(String msrp) {
        this.msrp = msrp;
    }

    public void setCost(String cost) {
        this.cost = cost;
    }
}