package com.luigimoro.spring.tutorial.dynamodb.dao.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "smartphone")
public class Smartphone {

    public Smartphone() {}

    public Smartphone(String brand, String model, double price) {
        setBrand(brand);
        setModel(model);
        this.setPrice(price);
    }


    private String id;

    private String brand;
    private String model;
    private double price;
    private double screenSize;

    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexNames = "index_1")
    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    @DynamoDBIndexRangeKey(globalSecondaryIndexNames = "index_1")
    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public double getScreenSize() {
        return screenSize;
    }

    public void setScreenSize(double screenSize) {
        this.screenSize = screenSize;
    }
}
